name: Sync Github Open Data repository and its metadata to OpenCoDE.de
description: "Workflow to sync OpenCoDE and Github"

inputs:
  # OpenCoDE Metadata
  GROUP_ID:
    description: "OpenCoDE Grpup ID"
    default: "2781"
    required: true
  ACCESS_USER:
    description: "OpenCoDE publishing username"
    default: "RKIOpenData"
    required: true
  BRANCH:
    description: "Branch to checkout"
    default: "main"
    required: true
  # Repository metadata
  REPO_PATH:
    description: "The repository name must not start or end with a special character and must not contain consecutive special characters"
    default: ${{ github.event.repository.name }}
    required: true
  ZENODOJSON_PATH:
    description: "Path to Zenodo.json that contains the repository metadata"
    required: true
    default: "Metadaten/zenodo-invenio.json"

  # Enviroment variables
  OPENCODE_TOKEN:
    description: "Access Token for OpenCoDE User"
    required: true
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
    
runs:
  using: "composite"
  
  steps:
    - name: Get OpencoDE group path
      id: group_path
      shell: bash
      run: | 
        # Get OpencoDE group path
        GROUP_INFO=$(curl \
          --request GET "https://gitlab.opencode.de/api/v4/groups/${{inputs.GROUP_ID }}" \
          --header "PRIVATE-TOKEN: ${{ inputs.OPENCODE_TOKEN }}") 
        echo "GROUP_PATH="$(echo $GROUP_INFO | jq -r '.full_path' )"" >> $GITHUB_ENV
        echo "GROUP_PATH_URLENCODE="$(echo $GROUP_INFO | jq -r '.full_path' | sed 's/\//%2F/g' )"" >> $GITHUB_ENV
        
    - name: Adjust REPO_PATH acording to Gitlab constrains 
      shell: bash
      run: | 
        # Adjust REPO_PATH acording to Gitlab constrains
        echo "REPO_PATH_GITLAB="$(echo "${{ inputs.REPO_PATH }}" | sed 's/_-_/-/g; s/_-/-/g; s/-_/-/g')"" >> $GITHUB_ENV

    - name: Get zenodo.json metadata from Github Open Data repository
      shell: bash
      run: |
         # Get zenodo.json metadata from Github Open Data repository
         ZENODOJSON_URL=$(curl \
          --request GET https://api.github.com/repos/${{ github.repository }}/contents/${{ inputs.ZENODOJSON_PATH }} \
          --header "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.mercy-preview+json" \
          | jq -r '.download_url')

         # Add Zenodo metadata to enviroment
         echo "REPO_NAME="$(curl $ZENODOJSON_URL | jq -r '.title')"" >> $GITHUB_ENV
         echo "DESCRIPTION="$(curl $ZENODOJSON_URL | jq -r '.description'| head -c 2000)"" >> $GITHUB_ENV
         echo "TOPICS="$(curl $ZENODOJSON_URL| jq -r '[.subjects[].subject] | join(",")' | sed 's/ä/ae/g; s/ö/oe/g; s/ü/ue/g; s/ß/ss/g' )"" >> $GITHUB_ENV
      
    - name: Create OpenCoDE repository
      shell: bash
      run: |
        # Create OpenCoDE repository
        curl \
          --request POST "https://gitlab.opencode.de/api/v4/projects" \
          --header "PRIVATE-TOKEN: ${{ inputs.OPENCODE_TOKEN }}" \
          --data-urlencode "path=${{ env.REPO_PATH_GITLAB }}" \
          --data-urlencode "namespace_id=${{ inputs.GROUP_ID }}"

    - name: Update OpenCoDE repository metadata
      shell: bash
      run: |
        # Update OpenCoDE repository metadata
        response=$(curl \
          --request PUT "https://gitlab.opencode.de/api/v4/projects/${{ env.GROUP_PATH_URLENCODE }}%2F${{ env.REPO_PATH_GITLAB }}" \
          --header "PRIVATE-TOKEN: ${{ inputs.OPENCODE_TOKEN }}" \
          --data-urlencode "name=${{ env.REPO_NAME }}" \
          --data-urlencode "description=${{ env.DESCRIPTION }}" \
          --data-urlencode "topics=${{ env.TOPICS }}")
        echo "$response"

    - name: Make OpenCoDE repository public
      shell: bash
      run: |
        # Make OpenCoDE repository public
        response=$(curl \
          --request PUT "https://gitlab.opencode.de/api/v4/projects/${{ env.GROUP_PATH_URLENCODE }}%2F${{ env.REPO_PATH_GITLAB }}" \
          --header "PRIVATE-TOKEN: ${{ inputs.OPENCODE_TOKEN }}" \
          --data-urlencode "visibility=public")
        echo "$response"
        
    - name: Checkout Github repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        ref: ${{ inputs.BRANCH }}
        fetch-depth: '0'
        lfs: true

    - name: Pull Git LFS files (if LFS is enabled and used)
      shell: bash
      run: |
        if command -v git-lfs >/dev/null && git lfs track | grep -q .; then
          echo "Pulling Git LFS files..."
          git lfs pull
        else
          echo "Skipping LFS pull (not installed or not used)."
        fi

    - name: Push to OpenCoDE (special LFS handling for selected repos)
      shell: bash
      run: |
        set -euo pipefail

        # Ensure fresh remote (token may rotate)
        git remote remove opencode 2>/dev/null || true
        git remote add opencode "https://${{ inputs.ACCESS_USER }}:${{ inputs.OPENCODE_TOKEN }}@gitlab.opencode.de/${{ env.GROUP_PATH }}/${{ env.REPO_PATH_GITLAB }}.git"

        REPO_LOWER="$(echo "${{ env.REPO_PATH_GITLAB }}" | tr '[:upper:]' '[:lower:]')"

        if [[ "$REPO_LOWER" == "sars-cov-2-infektionen_in_deutschland" ]] \
          || [[ "$REPO_LOWER" == "burden_2020-krankheitslast_in_deutschland_und_seinen_regionen" ]] \
          || [[ "$REPO_LOWER" == "sars-cov-2-sequenzdaten_aus_deutschland" ]]; then

          echo "Special-case: pushing last 5 tags only for $REPO_LOWER"

          # Re-authenticate origin so both 'git fetch' and 'git lfs fetch' can access GitHub
          git remote set-url origin "https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          # Last 5 tags by creation date (oldest -> newest so prerequisites land first)
          mapfile -t TAGS < <(git for-each-ref --sort=creatordate --format='%(refname:strip=2)' refs/tags | tail -n 5)

          if (( ${#TAGS[@]} > 0 )); then
            # Be explicit: do not filter out tag refs for LFS
            git config --local lfs.fetchinclude ""
            git config --local lfs.fetchexclude ""

            for t in "${TAGS[@]}"; do
              echo "Preparing LFS and pushing tag: $t"

              # 1) Ensure the tag object exists locally (shallow fetch is enough)
              git fetch --no-tags --depth=1 origin "tag" "$t"

              # 2) Fetch the LFS blobs needed by this tag from GitHub (authenticated origin)
              #    Using the tag name as the refspec is sufficient; no need for refs/tags/<t>
              git lfs fetch origin "$t"

              # (Optional: sanity check — list any missing objects that would block upload)
              # git lfs ls-files --all | grep -E '\(missing\)' && echo "Warning: still missing LFS after fetch"

              # 3) Pre-upload those blobs to the OpenCoDE remote so the server hook passes
              git lfs push opencode "$t"

              # 4) Now push the tag ref itself
              git push opencode -f "$t"
            done
          else
            echo "No tags found; skipping tag pushes."
          fi

        else
          echo "Default: pushing all branches and all tags"
          git push opencode -f
          git push opencode -f --tags
        fi

