name: Create release on tag push
description: test
inputs:
  REF_NAME:
    description: ref name
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{inputs.REF_NAME}}
        release_name: Publikation ${{inputs.REF_NAME}}
        body: Publikation der Version ${{inputs.REF_NAME}} inklusive aktualisierter Metadaten
        draft: false
        prerelease: false
