name: Push metadata to Govdata-Repository
description: sends *.ttl metadata to a separate repository

inputs:
  source_file:
    description: 'filepath and name send needs to be uploaded to the other repo'
    default: 'Metadaten/govdata.ttl'
  destination_file_name:
    description: 'name of the file in the new repo'
    default: '${{github.event.repository.name }}.ttl'
  destination_repo:
    description: 'repo the file source file should be copied to'
    default: 'knutator2/Metadaten_Test'
  destination_folder:
    description: 'folder in the repo the file should be copied to'
    default: 'Datensaetze'
  user_email:
    description: 'email address to put into the copy commit'
    default: 'opendata@rki.de'
  user_name:
    description: 'user name to put into the commit'
    default: 'RKIOpenData'
  govdata_github_token:
    description: 'token to access remote github repositories'
    required: true
    
runs:
  using: "composite"
  steps:
  
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rename ttl with reponame
      run: cp ${{ inputs.source_file }} ${{inputs.destination_file_name}}
      shell: bash

    - name: Push dataset ttl to Govdata repository
      id: pushStep1
      continue-on-error: true
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.govdata_github_token }}
      with:
        source_file: ${{inputs.destination_file_name}}
        destination_repo: ${{inputs.destination_repo}}
        destination_folder: ${{inputs.destination_folder}}
        commit_message: 'adding ${{inputs.destination_file_name}}'
        user_email: ${{inputs.user_email}}
        user_name: ${{inputs.user_name}}

    - name: Retry push dataset ttl to Govdata repository
      id: pushStep2
      if: steps.pushStep1.outcome == 'failure'
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.govdata_github_token }}
      with:
        source_file: ${{inputs.destination_file_name}}
        destination_repo: ${{inputs.destination_repo}}
        destination_folder: ${{inputs.destination_folder}}
        commit_message: 'adding ${{inputs.destination_file_name}}'
        user_email: ${{inputs.user_email}}
        user_name: ${{inputs.user_name}}
