name: Update Github repository details 
description: "Updates the Github repository details from dataset metadata"

inputs:
  # Repository metadata
  REPO_PATH:
    description: "The repository name must not start or end with a special character and must not contain consecutive special characters"
    default: ${{ github.event.repository.name }}
    
  ZENODOJSON_PATH:
    description: "Path to Zenodo.json that contains the repository metadata"
    default: "Metadaten/zenodo.json"

  # Environment variables
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
    
  GITHUB_METADATA_TOKEN:
    description: "Github metadata Token"
    required: true
    
runs:
  using: "composite"
  
  steps:
    - name: Get zenodo.json metadata from Github Open Data repository
      shell: bash
      run: |
         ZENODOJSON_URL=$(curl --fail-with-body -sSL \
          --request GET https://api.github.com/repos/${{ github.repository }}/contents/${{ inputs.ZENODOJSON_PATH }} \
          --header "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.mercy-preview+json" \
          | jq -r '.download_url')

         # Process and add Zenodo metadata to environment
         KEYWORDS=$(curl --fail-with-body -sSL $ZENODOJSON_URL | jq -c '{
            names: (
              .keywords 
              | map(gsub("Ä"; "Ae") 
                     | gsub("Ö"; "Oe") 
                     | gsub("Ü"; "Ue") 
                     | gsub("ä"; "ae") 
                     | gsub("ö"; "oe") 
                     | gsub("ü"; "ue") 
                     | gsub(" "; "-")  # replace spaces by hyphens
                     | gsub(","; "")   # remove commas
                     | ascii_downcase) # convert to lower case
              | map(select(length <= 50))  # select only keywords wkith 50 characters or less (this is the max character limit of github)
              | .[:20]
            )
          }')
          DESCRIPTION=$(
              curl -fsSL "$ZENODOJSON_URL" |
              jq -c '{
                description:
                  (.description // "" 
                   | gsub("&nbsp;"; " ")
                   | gsub("&quot;"; "\"")
                   | gsub("&#39;"; "'\''")
                   | gsub("&apos;"; "'\''")
                   | gsub("&amp;"; "&")
                   | gsub("&lt;"; "<")
                   | gsub("&gt;"; ">")
                   | gsub("<[^>]+>"; "")
                   | gsub("\n"; " ")
                   | if length > 350 then .[:347] + "..." else . end)
              }'
            )
         echo "TOPICS=$KEYWORDS"
         echo "TOPICS=$KEYWORDS" >> $GITHUB_ENV
         echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
         
    - name: Update GitHub topics and description
      shell: bash
      run: |
          set -e
          # Update GitHub topics
          curl --fail-with-body -sSL \
            -X PUT \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ inputs.GITHUB_METADATA_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/topics \
            -d "${TOPICS}"
            
          # Update GitHub description
          curl --fail-with-body -sSL \
            -X PATCH \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ inputs.GITHUB_METADATA_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }} \
            -d "${DESCRIPTION}"
